# Generated by Django 4.0.3 on 2022-04-11 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclubapp', '0006_alter_profile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'MALE'), ('DRAMA', 'DRAMA'), ('MYSTER', 'OTHER')], default='', max_length=6),
        ),
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='', upload_to='img'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='avatar',
            field=models.ImageField(default='avatar.jpg', upload_to='profile_images'),
        ),
    ]
