# Generated by Django 4.0.3 on 2022-04-11 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclubapp', '0007_movie_genre_alter_movie_image_alter_profile_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(choices=[('ACTION', 'ACTION'), ('DRAMA', 'DRAMA'), ('MYSTERY', 'MYSTERY')], default='', max_length=7),
        ),
    ]
