# Generated by Django 4.0.4 on 2022-04-12 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('videoclubapp', '0009_movie_dislikes_movie_likes'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='movies',
            field=models.ManyToManyField(blank=True, default='', to='videoclubapp.movie'),
        ),
    ]
